### ISSUE TITLE
Warn when the interceptor is not added, fail with an exception

### ISSUE THREAD

**Issue by jsgoupil** [VariableNotFound/ef6-tagwith#3]
I think by default, using TagWith without the interceptor installed should fail with an exception.
I have multiple projects using a Common library; I have forgotten to add the `QueryTaggerInterceptor` on a couple of projects, and instead of throwing an exception, it simply fails silently. The where clause is not reworked and it does not return any results.

**Comment by jmaguilar** [comment]
Absolutely agree, it should work this way. I'll work for fixing it and hope I'll release an update in the next few days.

Thanks for commenting!

**Comment by jsgoupil** [comment]
@jmaguilar Sorry to bug you on this bug, but did you get it to work on Query Performance Insight in the Azure Portal? the SQL comments don't show up in the Query Details.

**Comment by jmaguilar** [comment]
It seems that Query Performance Insights trims the query comments, so it would not be possible :( But it is not something related to TagWith, it also occurs if you send a query with a comment via SQL Server Management or a similar tool. 

Anyway, you'll be able to see the comments if you use one of the well-known queries to get the latest queries executed from your (Azure) SQL Server, such as:

```
SELECT dest.TEXT AS [Query],
deqs.execution_count [Count],
deqs.last_execution_time AS [Time]
FROM sys.dm_exec_query_stats AS deqs
CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest
ORDER BY deqs.last_execution_time DESC
```

BTW, if you find a way to make it be shown directly in Query Insights, feel free to let me know and I'll include the fix in the library :)

**Comment by jsgoupil** [comment]
Thanks @jmaguilar , I'll keep that query you gave me, that's handy. I know the comments being trimmed is not related to TagWith, no worries.

I was able to find the queries with a Profiler, but with that SELECT you gave me above, I don't think I find the comments either. There must be some settings

If you want to continue this conversation on gitter.im, search for me "jsgoupil"

Thanks!

**Comment by henrym** [comment]
@jmaguilar I was working on this issue a few months ago.

One solution I found was to insert the tags infix, e.g. after the SELECT:
```
SELECT
-- TagWith comment here
    Id,
    Name,
    Etc
FROM Table
```
I did some work on it back then, so I'll create an issue and do my best to find time over the weekend to fix it up and submit a PR.

**Comment by jmaguilar** [comment]
Great @henrym! 

It is a good idea and I think it could work with no downsides. The only problem I can see is that if we are using queries like the metioned in this issue, it'll be more difficult to see the comment because it won't appear at the beggining of the query. 

So I was wondering if this way of tagging could be a documented setting for not breaking the current behavior. Something like:

```
TagWith.Configure(op => opt.CommentLocation = CommentLocation.Infix);
// or
TagWith.Configure(new TagWithOptions() { ... });
```
Also, we could use this Configure() thing to add the interceptor so the initialization story could be cleaner.

What do you think?

**Comment by jsgoupil** [comment]
I'm sorry I brought 2 issues into one :see_no_evil:
Here are a couple of queries you might want to consider I see in Azure.

The idea of going with .Configure makes sense if you are on .NET Core.
I'm sure you can keep the old code working, but I would say keep the documentation as well because a couple of my projects MVC5. Others run in WebJobs ```host.RunAndBlock()```

** With a variable **
```
(@EntityKeyValue1 int)SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[ParentId] AS [ParentId], 
    [Extent1].[PartItemId] AS [PartItemId]
    FROM [dbo].[PriceBookCategoryPartItems] AS [Extent1]
    WHERE [Extent1].[PartItemId] = @EntityKeyValue1
```

** Without a variable **
```
SELECT 
    [Project2].[ServiceRepairId] AS [ServiceRepairId], 
    [Project2].[C1] AS [C1], 
...
```

** Without a ENTER **
```
(@__workOrderId_0 int)SELECT [m].[WorkOrderPaymentId], [m].[Amount], [m].[Confirmation], [m].[CreatedBy], [m].[CreatedDate], [m].[PaymentTypeId], [m].[RecordStatus], [m].[UpdatedBy], [m].[UpdatedDate], [m].[WorkOrderId]
FROM [WorkOrderPayments] AS [m]
WHERE [m].[WorkOrderId] = @__workOrderId_0
```
