### ISSUE TITLE
Add support for .NET core

### ISSUE THREAD

**Issue by jsgoupil** [VariableNotFound/ef6-tagwith#5]
.NET Core 3.1 supports EF6

```
warning NU1701: Package 'EF6.TagWith 1.0.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```

**Comment by jmaguilar** [comment]
Although the component seems to work fine, this warning message and the exclamation sign shown in the project references are a bit annoying.

I've working on the migration to .NET Standard, so it'll work in both .NET Framework and .NET Core projects. I've just published in Nuget a [preview package](https://www.nuget.org/packages/EF6.TagWith/1.1.0-preview1) to check if the warning has dissapeared and everything works fine. Please check if this works for you.

Thanks!

**Comment by jsgoupil** [comment]
Could you publish the fixes here please?
The preview seems to remove the warning.

**Comment by jmaguilar** [comment]
I've just uploaded a preview2 package solving some issues with references, so please update it to check if it works.

You can find the changes in the branch [jmaguilar/netstandard](https://github.com/VariableNotFound/ef6-tagwith/tree/jmaguilar/netstandard).

**Comment by jsgoupil** [comment]
seems fine
